name: $(date:yyyyMMdd)$(rev:.rr) #20191209.10

trigger:
  - master


stages:
  - stage: compile
    jobs:
      - job: aspnet
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: dotnet build 3_devops/DevopsTrial.sln
  - stage: test
    jobs:
      - job: aspnet_test
        pool:
          vmImage: ubuntu-18.04
        steps:
          - script: dotnet test 3_devops/DevopsTrial.sln --collect:"XPlat Code Coverage"
    